kind: pipeline
type: docker
name: pygoodwe

steps:
- name: testbuild
  image: python:3.7
  commands:
  - pip install -q pytest requests pylint loguru
  - pylint aussiebb
  - pytest
  environment:
    username:
      from_secret: username
    password:
      from_secret: password
    username2:
      from_secret: username2
    password2:
      from_secret: password2
    LOGURU_LEVEL: WARNING
