kind: pipeline
type: docker
name: pygoodwe

steps:
- name: testbuild
  image: python:3.7
  commands:
  - pip install pytest requests pylint loguru
  - pylint
  - pytest
  environment:
    username:
      from_secret: username
    password:
      from_secret: password
